[package]
name = "advent-2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.0"

[lib]
name = "advent"
path = "src/lib.rs"

[[bin]]
name = "advent_bin"
path = "src/bin.rs"
